USE [master]
GO

CREATE DATABASE [CLOB]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CLOB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CLOB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [CLOB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [CLOB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [CLOB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [CLOB] SET ARITHABORT ON 
GO

ALTER DATABASE [CLOB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CLOB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CLOB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CLOB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CLOB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [CLOB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [CLOB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CLOB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [CLOB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CLOB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CLOB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CLOB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CLOB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CLOB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CLOB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CLOB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CLOB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CLOB] SET RECOVERY FULL 
GO

ALTER DATABASE [CLOB] SET  MULTI_USER 
GO

ALTER DATABASE [CLOB] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [CLOB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CLOB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CLOB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CLOB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CLOB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CLOB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CLOB] SET  READ_WRITE 
GO

